# This is a resource index file for testing.
# All the content in this file is generated by the game editor.
# ** DO NOT MODIFY THE CONTENT BELOW WITHOUT ANY EXPERIENCE **

[FONTS]
1 fonts/Mars Police Italic.ttf
2 fonts/Elements.ttf
3 fonts/INTERDIM.TTF
$

[SAMPLE]
1 textures/one.png LINEAR
2 textures/two.png LINEAR
3 textures/three.png LINEAR
4 textures/animTestSrc.png NEAREST
5 textures/btn_begin.png LINEAR
6 textures/btn_exit.png LINEAR
7 textures/tile.png LINEAR
$

[ANIMATION]
1 animations/player.fba
$

[SOUND]
0 sounds/Default.wav
1 sounds/Button_01.wav
$

[MUSIC]
0 music/hardcore_01.wav
$

[SHADER]
1 shaders/uniformTest.so
2 shaders/TextureDiscarding.so
3 shaders/GreyScalePFX.so
4 shaders/basicTexture.so
$