# This is a resource index file for testing.
# Every line under header FONTS means a specific font need to be loaded.
# Every line under header SAMPLE means a specific texture need to be loaded.
# All the content in this file is generated by the game editor.
# ** DO NOT MODIFY THE CONTENT BELOW WITHOUT ANY EXPERIENCE **

[FONTS]
1 fonts/INTERDIM.TTF
$

[SHADER]
1 shaders/BasicPoints.so
$