# This is a resource index file for testing.
# Every line under header FONTS means a specific font need to be loaded.
# Every line under header SAMPLE means a specific texture need to be loaded.
# All the content in this file is generated by the game editor.
# ** DO NOT MODIFY THE CONTENT BELOW WITHOUT ANY EXPERIENCE **

[FONTS]
1 data/fonts/Mars Police Italic.ttf
2 data/fonts/Elements.ttf
3 data/fonts/INTERDIM.TTF
$

[SAMPLE]
5 data/textures/btn_begin.png LINEAR
6 data/textures/btn_exit.png LINEAR
$

[SOUND]
0 data/sounds/Default.wav
1 data/sounds/Button_01.wav
$